changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:
      - dependabot
  categories:
    - title: 🚨 Breaking Changes
      labels:
        - breaking-change
        - breaking
    - title: ✨ New Features
      labels:
        - feature
        - enhancement
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
        - bugfix
    - title: 🔧 Improvements
      labels:
        - improvement
        - refactor
        - performance
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🧪 Testing
      labels:
        - test
        - testing
    - title: 🏗️ Chores
      labels:
        - chore
        - maintenance
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
